version: '3.1'
networks:
  ads_scan_explorer_network:
      name: ads_scan_explorer_network
services:
  ads_scan_explorer_cantaloupe:
    image: uclalibrary/cantaloupe:5.0.4-1
    container_name: cantaloupe
    ports:
      - "8182:8182"
    environment:
      - "CANTALOUPE_SOURCE_STATIC=S3Source"
      - "CANTALOUPE_S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME=scan-explorer" 
      - "CANTALOUPE_S3SOURCE_ACCESS_KEY_ID=CHANGE_ME"
      - "CANTALOUPE_S3SOURCE_SECRET_KEY=CHANGE_ME"
    networks:
      - ads_scan_explorer_network