version: '3.1'
networks:
  ads_scan_explorer_network:
      name: ads_scan_explorer_network
services:
  ads_scan_explorer_cantaloupe:
    image: uclalibrary/cantaloupe:5.0.4-1
    container_name: cantaloupe
    ports:
      - "8182:8182"
    volumes:
      - ./cantaloupe.properties:/etc/cantaloupe.properties
    networks:
      - ads_scan_explorer_network